services:
  openwebui:
    image: openwebui/latest
    container_name: openwebui
    ports:
      - "3000:8080"
    environment:
      WEBUI_ENV: ${WEBUI_ENV}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "0.5"
        reservations:
          memory: 512M

  flowise:
    image: flowise/flowise:latest
    container_name: flowise
    ports:
      - "3101:3000"  
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "0.5"
        reservations:
          memory: 512M

  unstructuredapi:
    image: unstructuredio/api:latest
    container_name: unstructuredapi
    ports:
      - "3301:8000"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "1.0"
        reservations:
          memory: 1G

  tensorflow-serving:
    image: tensorflow/serving:latest
    container_name: tensorflow_serving
    ports:
      - "8501:8501"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: "2.0"
        reservations:
          memory: 2G

  torchserve:
    image: pytorch/torchserve:latest
    container_name: torchserve
    ports:
      - "8081:8080"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: "2.0"
        reservations:
          memory: 2G

  langchain:
    image: langchain/langchain:latest
    container_name: langchain
    ports:
      - "3400:3400"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "1.0"
        reservations:
          memory: 1G

  haystack:
    image: deepset/haystack:latest
    container_name: haystack
    ports:
      - "3500:8000"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: "2.0"
        reservations:
          memory: 2G

  mlflow:
    image: mlflow/mlflow:latest
    container_name: mlflow
    ports:
      - "3600:5000"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "1.0"
        reservations:
          memory: 1G

volumes:
  openwebui-data:
  flowise-data:
  unstructuredapi-data:
  tensorflow-data:
  torchserve-data:
  langchain-data:
  haystack-data:
  mlflow-data:
