services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"  # Default Redis port
    volumes:
      - redis-data:/data
    command: ["redis-server"]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
        reservations:
          memory: 256M

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"  # Default PostgreSQL port
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "1.0"
        reservations:
          memory: 1G

  milvus:
    image: milvusdb/milvus:latest
    container_name: milvus
    environment:
      MILVUS_LOG_LEVEL: ${MILVUS_LOG_LEVEL}
    ports:
      - "19530:19530"  # Default Milvus gRPC port
      - "19121:19121"  # Default Milvus HTTP port
    volumes:
      - milvus-data:/var/lib/milvus
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: "2.0"
        reservations:
          memory: 2G

volumes:
  redis-data:
    driver: local
  postgres-data:
    driver: local
  milvus-data:
    driver: local
